### ISSUE TITLE
FactoryGirl => FactoryBot Name Change

### ISSUE THREAD

**Issue by jonmchan** [markburns/to_factory#19]
The project FactoryGirl got renamed to FactoryBot. This breaks compatibility with this gem. Could we update to_factory with the new name?

https://github.com/thoughtbot/factory_bot/blob/4-9-0-stable/UPGRADE_FROM_FACTORY_GIRL.md

**Comment by jonmchan** [comment]
All code changes necessary have already been made in https://github.com/trh/to_factory/commit/4a716bf8d7cdc742ff21af200081f77be1d392d2#comments. All you have to do is merge it in and make a new release.

**Comment by markburns** [comment]
Addressed in #21
