### ISSUE TITLE
undefined method `ToFactory' for main:Object

### ISSUE THREAD

**Issue by Olgagr** [markburns/to_factory#5]
I'm getting this error when I do:
```ruby
ToFactory()
```

As I can see the to_factory.rb file only contains:

```
require "to_factory/version"
require "to_factory/generator"
```

Please update gem code on rubygems, as right now the gem doesn't work.

**Comment by markburns** [comment]
Sounds like you have an old version - looking at the tags 
v0.0.3 from 2011 is the latest one that has that code.

Updating should fix this

**Comment by Olgagr** [comment]
Yes, I see on rubygems the code is updated. Today added to_factory, without version, to my gemfile and bundler installed version '0.0.1'. Strange.

**Comment by markburns** [comment]
Maybe you already had it installed on your system?

**Comment by Olgagr** [comment]
Ok, I know whats going on. The dependencies:
 when I try to get 'to_factory' in version 0.2.0 I get:

```
Bundler could not find compatible versions for gem "activerecord":
  In snapshot (Gemfile.lock):
    activerecord (4.1.8)

  In Gemfile:
    to_factory (= 0.2.0) ruby depends on
      activerecord (< 4.0, > 2.0) ruby
```

**Comment by markburns** [comment]
OK I've not tried it in a Rails 4 app - basically I've been using this project with legacy apps. Generally newer apps I encounter tend to have tests and everything already.

Will open an issue for Rails 4 support - also happy to accept a PR for this if you are interested?
