### ISSUE TITLE
Rails 4 support

### ISSUE THREAD

**Issue by markburns** [markburns/to_factory#7]
See #5 we are currently restricting the version to < 4. 

I think the dependency complexities might require just having a new ToFactory version of the gem for Rails 4 and up.

**Comment by Olgagr** [comment]
Mark, can I ask you something? I see in gemspec file that there is a condition: 

```
  old_active_record = RUBY_VERSION =~ /^1\.8|^1.9\.[1|2]/

  spec.add_dependency "ruby2ruby"

  if old_active_record
    spec.add_dependency  'activerecord', ">2.0", "< 4.0"
    spec.add_dependency  'i18n', "< 0.7"
    spec.add_development_dependency "factory_girl", "< 2.0"
  else
    spec.add_dependency  'activerecord', ">3.0"
    spec.add_development_dependency "factory_girl", "~> 4.5"
  end
```

So activerecord version, for Ruby 1.9.3+ should resolve correctly. Foe example I have version 2.1.3 for Ruby.

**Comment by Olgagr** [comment]
Ok, rubygems doesn't support conditional dependency.

**Comment by markburns** [comment]
Yeah rubygems will probably just evaluate the gemspec with whatever interpreter they are running.
Up until now I've generally been developing this against a small set of applications locally, so I'm evaluating the gemspec with the version I'm targetting.

I'm open to ideas for how to provide support for a wider set of applications.

Possibly getting rid of this stuff and having branches. I guess I'd like to see if people are using this then what issues they run into and how best to support it from that perspective. A matrix of dependencies would be pretty involved and hard to test and probably overkill. E.g. ruby interpreter version, AR version, FactoryGirl version.
However, this binary choice of old vs new referring to AR version/FactoryGirl syntax version and ruby version is obviously not ideal either. (It just happens to work for my case).

From your perspective, if it's Rails 4.x support, then removing all this cruft and reducing dependencies sounds good. We could maybe have a branch that only supports all the new stuff and specifiies just minimum versions for the dependencies.

**Comment by Olgagr** [comment]
I created new branch, dependencies are only for Ruby 1.9.3+ (https://github.com/Olgagr/to_factory/tree/ruby_1_9_3%2B_support). Do you have any experience with adding extensions to gemspec file? I think we can add extension to install proper version of gem, depending on which version of Ruby is used. However, I've never used extension before, so not sure if this works. If it works we could just bump up gem version to 1.0.0 and it should works for older version of Ruby as well.

**Comment by markburns** [comment]
I don't have any experience with this but it looks interesting.

From a practical perspective, you might want to just ignore supporting any use cases you personally aren't interested in and just seeing what if any code changes are needed to get Rails 4 support working, ignoring the rest.

Once that works then we could look at options for supporting different rubies etc.

However, it's up to you. If this is more fun and the goal isn't just to get Rails 4 support, but to learn something and introduce an overall better solution then by all means go for it.

**Comment by markburns** [comment]
Compared @Olgagr 's approach with the appraisals gem and decided to go with v1.x for older stuff, then v2.x for newer stuff. 

Rails 4 support now in 2.0.0 gem

**Comment by markburns** [comment]
Also thanks @Olgagr !
